version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/app'
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"

  - package-ecosystem: 'npm'
    directory: '/api'
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
