version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 15
    schedule:
      interval: "daily"

    ignore:
      - # Stay on node lts
        dependency-name: '@types/node'
        versions:
          - '>= 15'
      - # eslint-vue-plugin does not support eslint 8 in versions < 5
        # https://github.com/vuejs/vue-cli/issues/6759
        dependency-name: 'eslint'
        versions:
          - '>= ^8.0.0'



