version: '3'
services:
    mate-postgres:
      image: postgres:11
      container_name: mate-postgres
      environment:
        - POSTGRES_USER=mate-user
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DB=mate-db
      volumes:
        - postgres-volume:/var/lib/postgresql/data
      ports:
        - 127.0.0.1:5432:5432

volumes:
  postgres-volume:
