version: '3'
services:
    mate-postgres:
      image: postgres:13
      container_name: mate-postgres
      environment:
        - POSTGRES_USER=mate-user
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DB=mate-db
      volumes:
        - postgres-volume:/var/lib/postgresql/data
      ports:
        - 127.0.0.1:5432:5432

    adminer:
      image: adminer:latest
      depends_on:
        - mate-postgres
      environment:
        ADMINER_DESIGN: nette
      ports:
        - 127.0.0.1:8000:8080
      depends_on:
        - mate-postgres

volumes:
  postgres-volume:
