name: build latest

on:
  # remove before merge
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-production-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t ghcr.io/matekasse/matekasse:latest . >
          docker push ghcr.io/matekasse/matekasse:latest