name: build latest docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-latest-image-multiarch:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install buildx dependencies
        run: sudo apt-get update && sudo apt-get install qemu qemu-user-static binfmt-support debootstrap -y
      - name: Install other stuff
        run: sudo apt-get update && sudo apt-get install python3 -y
      - name: Create buildx builder
        run: docker buildx create --name arm-builder
      - name: Use buildx builder
        run: docker buildx use arm-builder
      - name: Build Docker image
        run: docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 -t ghcr.io/matekasse/matekasse:latest_multiarch_slim_purge_no_stuff_frontend_build -f Dockerfile . --push

#,linux/amd64,linux/arm/v7