name: build latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-latest-image-x86:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ghcr.io/matekasse/matekasse:latest_test .
      - name: Push Docker image
        run: docker push ghcr.io/matekasse/matekasse:latest_test

  build-latest-image-ARM:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare buildx
        run: docker buildx create --name arm-builder
      - name: Prepare buildx 2
        run: docker buildx use arm-builder
      - name: Build Docker image
        run: docker buildx build --platform linux/amd64,linux/arm/v7 -t ghcr.io/matekasse/matekasse:latest_multiarch -f Dockerfile_arm . --push
