name: build latest

on:
  # remove before merge
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-production-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
      - name: Build docker image
        run: docker build -t ghcr.io/matekasse/matekasse:latest .
      - name: Push docker image
        run: docker push ghcr.io/matekasse/matekasse:latest