name: build latest testing docker image

on:
  push:
    branches:
      - main


jobs:
  build-latest-image-multiarch:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ghcr.io/matekasse/matekasse:latest_testing -f Dockerfile .
