name: complete integration test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  complete-integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update system and install browser
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install firefox
          sudo apt-get install chromium-browser
      - name: Build matekasse docker
        run: docker build -t ghcr.io/matekasse/matekasse:latest -f Dockerfile .
      - name: Change port in docker-compose
        run: |
          sed -i 's|0.0.0.0:1337|0.0.0.0:8080|g' docker-compose.yaml
      - name: Start docker environment
        run: docker-compose up -d
      - name: Install testcafe and dependencies
        run: cd testcafe && yarn install
      - name: Run tests firefox
        run: cd testcafe/tests && yarn testcafe "firefox:headless" tests/basic-test.js
      - name: Reset docker environment
        run: |
          docker-compose down
          docker volume rm matekasse_postgres-volume
          docker-compose up -d
          sleep 10
      - name: Run tests chromium
        run: cd testcafe/tests && yarn testcafe "chromium:headless" tests/basic-test.js