name: complete integration test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Runs all steps on the VM
  # The service containers will use host port binding instead of container networking so you access them via localhost
  # rather than the service name.

  complete-integration-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: postgres:13
        env:
            POSTGRES_DB: mate-db
            POSTGRES_USER: mate-user
            POSTGRES_PASSWORD: "1234"
            DBPORT: "5432"
            DBHOST: postgres
            SECRET: "SECRETKEY"

        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update and install browser
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install firefox
          sudo apt-get install chromium
      - name: Install yarn packages
        run: yarn install
      - name: Start backend
        run: cd api && ENVIRONMENT=development SECRET="notsosecretdev" DATABASE_CONNECTION_URL="postgresql://mate-user:1234@127.0.0.1:5432/mate-db"  yarn start:dev &
      - name: Start frontend
        run: cd app && yarn &
      - name: Install testcafe
        run: cd testcafe && yarn install
      - name: Run tests firefox
        run: cd testcafe/tests && yarn testcafe "firefox:headless" tests/testcafe/basic-test.js
      - name: Run tests chromium
        run: cd testcafe/tests && yarn testcafe "chromium:headless" tests/testcafe/basic-test.js