name: lint backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install yarn packages
        run: cd api && yarn install
      - name: lint
        run: cd api && yarn lint
