name: test multiarch-build

on:
  push:
    branches:
      - main
    paths:
      - "yarn.lock"
  pull_request:
    branches:
      - main
    paths:
      - "yarn.lock"

jobs:
  test-build-image-multiarch:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install buildx dependencies
        run: sudo apt-get update && sudo apt-get install qemu qemu-user-static binfmt-support debootstrap -y
      - name: Create buildx builder
        run: docker buildx create --name arm-x86-multi-builder
      - name: Use buildx builder
        run: docker buildx use arm-x86-multi-builder
      - name: Build Docker image latest
        run: docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/matekasse/matekasse:test -f Dockerfile .
