name: test frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install yarn packages
        run: cd app && yarn install
      - name: build app
        run: cd app && yarn build
